<<<<<<< HEAD
[build]
publish = "."
command = ""

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
=======
[build]
publish = "."
command = ""

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
>>>>>>> e6f1041586b2e7c8430b3fe613a2964e244a64fc
